### ISSUE TITLE
config_enabled_lte should be set to true in overlay

### ISSUE THREAD

**Issue by prurigro** [CarbonROM/android_device_google_wahoo#1]
Unlike marlin and sailfish, the overlay for wahoo/taimen/walleye doesn't include `<bool name="config_enabled_lte" translatable="false">true</bool>` for the Telephony service (see: https://github.com/CarbonROM/android_device_google_marlin/blob/cr-6.0/overlay/packages/services/Telephony/res/values/config.xml#L25)

Without this set, LTE/4G doesn't appear in the `Preferred network type` option in mobile network settings.

There are a few other settings in the marlin overlay that might be worth pulling in as well, but this one I've tested builds for in both directions for and it's definitely required.

Cheers!

**Comment by Myself5** [comment]
Shows just fine here:
https://myself5.de/Screenshot_20171207-220658.png

**Comment by prurigro** [comment]
Huh, so it does-- I was using your device profiles for a custom build off AOSP and didn't realize you had your own menu in Carbon. I might have to build 6.1 and see how she runs! Sorry for the bother :)
